# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f9afe544dc68646a8300d0467cdae7d0e252b0c8d4ad817be0d1eb376179b290af3082c5d97c939ffe566ccb04011120e9d05ddbf845719e6261c6ea5fe9db45

test:
  secret_key_base: adac0fcc1718febc954355a05daef0fd64420afdcac2fcf92110f19d45ce57776c256b477a0d9e9364747690a15a94a332ee1105f90c130614c08c012ba228ba

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
